// Code generated by "bson_corpus_spec_test_generator.go"; DO NOT EDIT

package bson_test

import (
	"testing"

	"github.com/10gen/mongo-go-driver/bson"
	"github.com/stretchr/testify/require"
)

func testValid(t *testing.T, in []byte, expected []byte, result interface{}) {
	err := bson.Unmarshal(in, result)
	require.NoError(t, err)

	out, err := bson.Marshal(result)
	require.NoError(t, err)

	require.Equal(t, string(expected), string(out))
}

func testDecodeSkip(t *testing.T, in []byte) {
	err := bson.Unmarshal(in, &struct{}{})
	require.NoError(t, err)
}

func testDecodeError(t *testing.T, in []byte, result interface{}) {
	err := bson.Unmarshal(in, result)
	require.Error(t, err)
}
