// Copyright (C) MongoDB, Inc. 2017-present.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

// Code generated by drivergen. DO NOT EDIT.

package driverx

import (
	"go.mongodb.org/mongo-driver/mongo/readpref"
	"go.mongodb.org/mongo-driver/x/mongo/driver/session"
	"go.mongodb.org/mongo-driver/x/network/description"
)

func (ao AggregateOperation) Client(client session.Client) AggregateOperation {
	ao.client = &client
	return ao
}

func (ao AggregateOperation) Clock(clock session.ClusterClock) AggregateOperation {
	ao.clock = &clock
	return ao
}

func (ao AggregateOperation) ReadPref(readPref readpref.ReadPref) AggregateOperation {
	ao.readPref = &readPref
	return ao
}

// ServerSelector sets the selector used to retrieve a server from a Deployment.
func (ao AggregateOperation) ServerSelector(serverSelector description.ServerSelector) AggregateOperation {
	ao.serverSelector = serverSelector
	return ao
}
