package driverx

import (
	"context"
	"errors"

	"go.mongodb.org/mongo-driver/mongo/readpref"
	"go.mongodb.org/mongo-driver/mongo/writeconcern"
	"go.mongodb.org/mongo-driver/x/bsonx/bsoncore"
	"go.mongodb.org/mongo-driver/x/mongo/driver/session"
	"go.mongodb.org/mongo-driver/x/network/description"
	"go.mongodb.org/mongo-driver/x/network/result"
)

//go:generate drivergen -use-pointers -constructor Insert InsertOperation insert.generated.go

var msgInsert = [...]byte{'d', 'o', 'c', 'u', 'm', 'e', 'n', 't', 's', 0x00}

type InsertOperation struct {
	insert struct{} `drivergen:",commandName"`

	// Documents adds documents to this operation that will be inserted when this operation is
	// executed.
	documents []bsoncore.Document `drivergen:",variadic,constructorArg"`

	// Ordered sets ordered. If true, when a write fails, the operation will return the error, when
	// false write failures do not stop execution of the operation.
	ordered *bool

	// WriteConcern sets the write concern for this operation.
	writeConcern *writeconcern.WriteConcern `drivergen:",pointerExempt"`

	// BypassDocumentValidation allows the operation to opt-out of document level validation. Valid
	// for server versions >= 3.2. For servers < 3.2, this setting is ignored.
	bypassDocumentValidation *bool

	// Retry enables retryable writes for this operation. Retries are not handled automatically,
	// instead a boolean is returned from Execute and SelectAndExecute that indicates if the
	// operation can be retried. Retrying is handled by calling RetryExecute.
	retry *RetryMode `drivergen:",retryableWrite"`

	// Namespace sets the database and collection to run this operation against.
	ns Namespace `drivergen:"Namespace"`

	// Deployment sets the deployment to use for this operation.
	d Deployment `drivergen:"Deployment"`

	// ServerSelector sets the selector used to retrieve a server.
	serverSelector description.ServerSelector

	// Session sets the session for this operation.
	client *session.Client `drivergen:"Session,pointerExempt"`

	// ClusterClock sets the cluster clock for this operation.
	clock *session.ClusterClock `drivergen:"ClusterClock,pointerExempt"`

	result result.Insert `drivergen:"-"`
}

// Result returns the result from executing this operation. This should only be called after Execute
// and any retries.
//
// TODO(GODRIVER-617): This should be generated by drivergen.
func (io *InsertOperation) Result() result.Insert {
	if io == nil {
		return result.Insert{}
	}
	return io.result
}

func (io *InsertOperation) processResponse(response bsoncore.Document) error {
	if n, ok := response.Lookup("n").AsInt64OK(); ok {
		io.result.N += int(n)
	}
	return nil
}

// TODO(GODRIVER-617): This should be generated by drivergen.
func (io *InsertOperation) selectServer(ctx context.Context) (Server, error) {
	if io.d == nil {
		return nil, errors.New("InsertOperation must have a Deployment set before Select can be called.")
	}

	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	default:
	}

	return io.d.SelectServer(ctx, createReadPrefSelector(readpref.Primary(), io.serverSelector))
}

// TODO(GODRIVER-617): This should be generated by drivergen.
func (io *InsertOperation) retryable(desc description.Server) bool {
	return (io.retry != nil && (*io.retry).Enabled()) && retrySupported(io.d.Description(), desc, io.client, io.writeConcern)
}

// TODO(GODRIVER-617): This should be generated by drivergen.
func (io *InsertOperation) Execute(ctx context.Context) error {
	if io.d == nil {
		return errors.New("InsertOperation must have a Deployment set before Select can be called.")
	}

	if io.client != nil && !writeconcern.AckWrite(io.writeConcern) {
		return errors.New("session provided for an unacknowledged write")
	}
	if io.ns.Collection == "" || io.ns.DB == "" {
		return errors.New("Collection and DB must be of non-zero length")
	}
	return writeOperationContext{
		writeOperation: io,

		tkind:      io.d.Description().Kind,
		db:         io.ns.DB,
		identifier: "documents",
		documents:  io.documents,

		client:  io.client,
		mode:    io.retry,
		ordered: io.ordered,
	}.execute(ctx)
}

// TODO(GODRIVER-617): This should be generated by drivergen.
func (io *InsertOperation) command(dst []byte, desc description.SelectedServer) ([]byte, error) {
	dst = bsoncore.AppendStringElement(dst, "insert", io.ns.Collection)

	if io.ordered != nil {
		dst = bsoncore.AppendBooleanElement(dst, "ordered", *io.ordered)
	}
	if io.bypassDocumentValidation != nil {
		dst = bsoncore.AppendBooleanElement(dst, "bypassDocumentValidation", *io.bypassDocumentValidation)
	}
	dst, err := addWriteConcern(dst, io.writeConcern)
	if err != nil {
		return dst, err
	}

	dst, err = addSession(dst, io.client, desc)
	if err != nil {
		return dst, err
	}

	if io.client.RetryWrite {
		dst = bsoncore.AppendInt64Element(dst, "txnNumber", io.client.TxnNumber)
	}

	dst = addClusterTime(dst, io.client, io.clock, desc)

	return dst, nil
}
