name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: The name of the new branch
        required: true
      version:
        description: The version to set on the branch
        required: true
      base_ref:
        description: The base reference for the branch
      push_changes:
        description: Whether to push the changes
        default: "true"
permissions:
  contents: read
concurrency:
  group: create-branch-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash -eux {0}
jobs:
  check-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.base_ref }}
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: Verify sbom.json is up to date
        run: EXPECT_ERROR=1 go run ./internal/cmd/generate-sbom
  regenerate-sbom:
    needs: check-sbom
    if: failure()
    uses: ./.github/workflows/sbom.yml
    with:
      ref: ${{ inputs.base_ref || github.ref }}
    permissions:
      contents: write
      pull-requests: write
  create-branch:
    needs: check-sbom
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    outputs:
      version: ${{ steps.pre-publish.outputs.version }}
    steps:
      - uses: mongodb-labs/drivers-github-tools/secure-checkout@2515c763d88282c570b47c895aa50e9e6f7ed32c #v3
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: mongodb-labs/drivers-github-tools/setup@2515c763d88282c570b47c895aa50e9e6f7ed32c #v3
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          aws_region_name: ${{ vars.AWS_REGION_NAME }}
          aws_secret_id: ${{ secrets.AWS_SECRET_ID }}
          artifactory_username: ${{ vars.ARTIFACTORY_USERNAME }}
      - uses: mongodb-labs/drivers-github-tools/create-branch@2515c763d88282c570b47c895aa50e9e6f7ed32c #v3
        id: create-branch
        with:
          branch_name: ${{ inputs.branch_name }}
          version: ${{ inputs.version }}
          base_ref: ${{ inputs.base_ref }}
          push_changes: ${{ inputs.push_changes }}
          version_bump_script: "go run ${{ github.action_path }}/bump-version.go"
          evergreen_project: mongo-go-driver-release
          release_workflow_path: ./.github/workflows/release.yml
