name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
        branch_name:
          description: The name of the new branch
          required: true
        version:
          description: The version to set on the branch
          required: true
        base_ref:
          description: The base reference for the branch
        push_changes:
          description: Whether to push the changes
          default: "true"

concurrency:
  group: create-branch-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -eux {0}

jobs:
  create-branch:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    outputs:
      version: ${{ steps.pre-publish.outputs.version }}
    steps:
      - uses: mongodb-labs/drivers-github-tools/secure-checkout@v2
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: mongodb-labs/drivers-github-tools/setup@v2
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          aws_region_name: ${{ vars.AWS_REGION_NAME }}
          aws_secret_id: ${{ secrets.AWS_SECRET_ID }}
          artifactory_username: ${{ vars.ARTIFACTORY_USERNAME }}
      - uses: mongodb-labs/drivers-github-tools/create-branch@v2
        id: create-branch
        with:
          branch_name: ${{ inputs.branch_name }}
          version: ${{ inputs.version }}
          base_ref: ${{ inputs.base_ref }}
          push_changes: ${{ inputs.push_changes }}
          version_bump_script: "go run ${{ github.action_path }}/bump-version.go"
          evergreen_project: mongo-go-driver-release
          release_workflow_path: ./.github/workflows/release.yml
